### ISSUE TITLE
Unable to import the Chess Solution into PowerApps due to missing dependiencies

### ISSUE THREAD

**Issue by RahmanBadru** [brasov2de/DragAndDropPCF#1]
Dear Team,

I tried to download the DragAndDropDemo_1_0_0_4.zip solution into my environment.

However, I got the error in the screenshot below:

![image](https://github.com/user-attachments/assets/3d0947c6-510b-40f8-8e55-7c93793311cd)

I have looked through the git repo and all the files but cannot seem to find the missing dependencies.

Please help
![Missing Dependencies](https://github.com/user-attachments/assets/68c42b3f-f566-456d-8fb7-e05598105aa1)

**Comment by brasov2de** [comment]
Hi @RahmanBadru , 

You've imported the demo solution, which only showcases how the DragAndDrop component works. In order to install it, you need the component first: which is inside the DragAndDropSolution_managed.zip.
You can find all the needed solutions in the releases folder: https://github.com/brasov2de/DragAndDropPCF/releases , navigate down to assets:
![image](https://github.com/user-attachments/assets/fc52b13e-2859-4550-925d-b08282c8f089)
